FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html
COPY admin.html /usr/share/nginx/html/admin.html
COPY brand-curious-cat.webp /usr/share/nginx/html/brand-curious-cat.webp

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
